# Dependencies
markdown: kramdown
highlighter: rouge

gems:
  - jekyll-sitemap

exclude: [vendor]

# Permalinks
permalink: /:title/

# Setup
title: 'NiOSLetter'
tagline: 'Uma newsletter sobre Swift.org'
timezone: America/Maceio

url: https://niosletter.github.io
handle: '@hdoria'

author:
  name: 'Hugo Doria'
  url: https://twitter.com/hdoria

excerpt_separator: <!--excerpt-->

links:
  twitter: 'https://twitter.com/hdoria'
  github: 'https://github.com/NiOSLetter/niosletter.github.io'
  issue: 'https://github.com/NiOSLetter/niosletter.github.io/issues/new'
  pull: 'https://github.com/NiOSLetter/niosletter.github.io/compare'

authors:
  jsq:
    name: 'Hugo Doria'
    twitter: '@hdoria'
    url: 'https://twitter.com/hdoria'
